version: "3.5"

services:
  simpleapp:
    container_name: simpleapp
    build:
      context: .
      dockerfile: SimpleApp/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5698

  sidecar:
    container_name: sidecar
    build:
      context: .
      dockerfile: SideCar/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5001
      - SideCarSettings__SelfPort=5001
      - SideCarSettings__AppPort=5698
    ports:
      - "5001:5001"